package modelo;
// Generated 17/12/2023 11:43:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamentos generated by hbm2java
 */
@Entity
@Table(name="departamentos"
    ,catalog="hibernatefinaljsf"
)
public class Departamentos  implements java.io.Serializable {


     private Integer iddepartamento;
     private String departamento;
     private String descripcion;
     private Set empleados = new HashSet();


    public Departamentos() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddepartamento", unique=true, nullable=false)
    public Integer getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(Integer iddepartamento) {
        this.iddepartamento = iddepartamento;
    }

    
    @Column(name="departamento", nullable=false, length=50)
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="descripcion", length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @OneToMany(mappedBy = "departamento", fetch = FetchType.LAZY)
    public Set getEmpleados() {
        return this.empleados;
    }

    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }


}


