package modelo;
// Generated 17/12/2023 11:43:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegistroVacaciones generated by hbm2java
 */
@Entity
@Table(name="registro_vacaciones"
    ,catalog="hibernatefinaljsf"
)
public class RegistroVacaciones  implements java.io.Serializable {


     private Integer idregistro;
     private Empleados empleados;
     private TipoVacaciones tipoVacaciones;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;

    public RegistroVacaciones() {
    }

    public RegistroVacaciones(Empleados empleados, TipoVacaciones tipoVacaciones, Date fechaInicio, Date fechaFin, String estado) {
       this.empleados = empleados;
       this.tipoVacaciones = tipoVacaciones;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idregistro", unique=true, nullable=false)
    public Integer getIdregistro() {
        return this.idregistro;
    }
    
    public void setIdregistro(Integer idregistro) {
        this.idregistro = idregistro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empleado_id", nullable=false)
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_id", nullable=false)
    public TipoVacaciones getTipoVacaciones() {
        return this.tipoVacaciones;
    }
    
    public void setTipoVacaciones(TipoVacaciones tipoVacaciones) {
        this.tipoVacaciones = tipoVacaciones;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", nullable=false, length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="estado", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


