package modelo;
// Generated 17/12/2023 11:43:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoVacaciones generated by hbm2java
 */
@Entity
@Table(name="tipo_vacaciones"
    ,catalog="hibernatefinaljsf"
)
public class TipoVacaciones  implements java.io.Serializable {


     private Integer idtipo;
     private String nombre;
     private String descripcion;
     private Set registroVacacioneses = new HashSet(0);
     private Set registroVacacioneses_1 = new HashSet(0);

    public TipoVacaciones() {
    }

	
    public TipoVacaciones(String nombre) {
        this.nombre = nombre;
    }
    public TipoVacaciones(String nombre, String descripcion, Set registroVacacioneses, Set registroVacacioneses_1) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.registroVacacioneses = registroVacacioneses;
       this.registroVacacioneses_1 = registroVacacioneses_1;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtipo", unique=true, nullable=false)
    public Integer getIdtipo() {
        return this.idtipo;
    }
    
    public void setIdtipo(Integer idtipo) {
        this.idtipo = idtipo;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoVacaciones")
    public Set getRegistroVacacioneses() {
        return this.registroVacacioneses;
    }
    
    public void setRegistroVacacioneses(Set registroVacacioneses) {
        this.registroVacacioneses = registroVacacioneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoVacaciones")
    public Set getRegistroVacacioneses_1() {
        return this.registroVacacioneses_1;
    }
    
    public void setRegistroVacacioneses_1(Set registroVacacioneses_1) {
        this.registroVacacioneses_1 = registroVacacioneses_1;
    }




}


